kind: ConfigMap
apiVersion: v1
metadata:
  name: notification-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: notification
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: notification
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notification
  template:
    metadata:
      labels:
        app: eshop
        service: notification
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: notification-api
          image: eshopdapr/notification.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notification-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: notification-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: notification
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    service: notification
